ARG NOTEBOOK_VERSION=latest
FROM jupyter/base-notebook:$NOTEBOOK_VERSION

# Once for the base installation
# RUN mamba install nb_conda_kernels
# The following is a workaround to fix the formatting of the kernel names
COPY --chown=1000 nb_conda_kernels /tmp/nb_conda_kernels
RUN mamba run pip install /tmp/nb_conda_kernels
RUN mamba run python -m nb_conda_kernels.install --enable

# One of these per environment (ipykernel is critical!)
RUN mamba create -n OME -c conda-forge -c ome --yes --quiet \
	bioformats2raw \
	ipykernel \
	napari-ome-zarr \
	omero-py \
	zarr
RUN mamba run -n OME pip install ezomero 

RUN mamba create -n EuBI -c euro-bioimaging --yes --quiet \
	eubi-bridge \
	ipykernel

# Be sure to build and tag the image with:
# docker build -t tim2025 -f Dockerfile.tim2025 .
